-- PostgreSQL Production Database Schema for Shree Precision Components
-- Domain Architecture: Manufacturing & Industry 4.0 Operations Platform (custom)
-- Generated by BizzMitra AI Engine
-- Problem Statement Reference:
-- "Our manufacturing company receives hundreds of supplier invoices every month through email, PDFs, WhatsApp images and physical documents. The finance team manually enters invoice data into spreadsheets and ERP systems, checks invoices against purchase orders and goods receipts, verifies GST details, identifies duplicate invoices, and follows up with different departments for approvals. This process is slow, error-prone and difficult to track. Invoices can remain pending for days because nobody has clear visibility of their approval status. Management also lacks a real-time view of outstanding liabilities, upcoming payments and exceptions. We need an enterprise SaaS platform that automatically captures invoice data, matches invoices with purchase orders and goods receipts, detects duplicates and discrepancies, routes invoices to the correct approver, and provides a centralized dashboard and audit trail."

CREATE TABLE IF NOT EXISTS public.custom_records (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  col1_data TEXT NOT NULL, -- Semantic Mapping: Operational Category
  col2_data TEXT NOT NULL, -- Semantic Mapping: Parameters & Scope
  status TEXT NOT NULL,    -- Semantic Mapping: Execution Stage
  badge TEXT DEFAULT 'Active',
  assignee TEXT NOT NULL,  -- Semantic Mapping: Assigned Lead
  metric_value TEXT NOT NULL, -- Semantic Mapping: SLA Turnaround
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.custom_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.custom_records
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Team and Role Authentication table
CREATE TABLE IF NOT EXISTS public.custom_users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  badge TEXT NOT NULL,
  department TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.custom_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read-write for authenticated users"
  ON public.custom_users
  FOR ALL
  USING (true)
  WITH CHECK (true);
